version: "3.7"

services:  
  postgres:
    container_name: postgres
    restart: always
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: 
      - "5432:5432"
